title: Creating my first blog .. ever
author: its me my name is Sultan 
email: sultanissa123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
writing this blog to complete the tutorial .. maybe i will write few things about myslef or mybe another things .. mmm 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
